export const antonimosBloque5: Record<string, string[]> = {
  abisal: ["superficial", "somero", "leve", "ligero", "banal"],
  abúlico: ["enérgico", "resuelto", "decidido", "volitivo", "activo"],
  acerado: ["blando", "suave", "flexible", "maleable", "dúctil"],
  acrimonioso: ["amable", "cordial", "afable", "benigno", "suave"],
  adocenado: ["original", "singular", "excepcional", "extraordinario", "inusual"],
  adusto: ["afable", "cordial", "amable", "benévolo", "risueño"],
  afásico: ["locuaz", "elocuente", "expresivo", "verbal", "hablador"],
  agorero: ["optimista", "esperanzado", "positivo", "confiado", "auspicioso"],
  alambicado: ["simple", "claro", "sencillo", "directo", "llano"],
  alicaído: ["vigoroso", "animado", "fuerte", "enérgico", "robusto"],

  anodadado: ["despierto", "alerta", "avispado", "atento", "espabilado"],
  apático: ["entusiasta", "ardiente", "dinámico", "activo", "vehemente"],
  apócrifo: ["auténtico", "veraz", "genuino", "fidedigno", "real"],
  apremiante: ["aplazable", "postergable", "evitable", "prescindible", "opcional"],
  arisco: ["afable", "sociable", "cordial", "amigable", "benigno"],
  arquetípico: ["atípico", "inusual", "singular", "raro", "extraño"],
  asiduo: ["esporádico", "ocasional", "intermitente", "eventual", "raro"],
  atrabiliario: ["apacible", "sereno", "sosegado", "tranquilo", "calmo"],
  austero: ["lujoso", "suntuoso", "fastuoso", "opulento", "ostentoso"],

  baladí: ["esencial", "grave", "importante", "trascendente", "fundamental"],
  balbuciente: ["elocuente", "fluido", "claro", "expresivo", "verbal"],
  beocio: ["culto", "sabio", "erudito", "docto", "ilustrado"],
  belicoso: ["pacífico", "conciliador", "tranquilo", "sereno", "apacible"],
  benéfico: ["perjudicial", "nocivo", "dañino", "lesivo", "nocente"],
  bizarro: ["cobarde", "pusilánime", "temeroso", "miedoso", "apocado"],
  cáustico: ["amable", "afable", "cordial", "benigno", "suave"],
  cicatero: ["generoso", "liberal", "dadivoso", "altruista", "magnánimo"],
  contiguo: ["distante", "lejano", "separado", "remoto", "apartado"],
  contumaz: ["dócil", "obediente", "flexible", "maleable", "sumiso"],

  decrépito: ["vigoroso", "robusto", "lozano", "fuerte", "saludable"],
  deleznable: ["sólido", "consistente", "firme", "estable", "resistente"],
  demacrado: ["lozano", "vigoroso", "robusto", "fuerte", "saludable"],
  desidioso: ["diligente", "activo", "laborioso", "aplicado", "solícito"],
  diáfano: ["opaco", "turbio", "oscuro", "nebuloso", "denso"],
  displicente: ["atento", "solícito", "amable", "cordial", "considerado"],
  dúctil: ["rígido", "férreo", "inflexible", "duro", "intransigente"],
  efímero: ["duradero", "perenne", "constante", "permanente", "estable"],
  elíptico: ["explícito", "claro", "directo", "manifiesto", "patente"],
  estólido: ["perspicaz", "agudo", "sagaz", "lúcido", "avispado"],

  farragoso: ["claro", "simple", "conciso", "directo", "sencillo"],
  fatuo: ["sensato", "juicioso", "prudente", "cuerdo", "sabio"],
  fétido: ["fragante", "aromático", "perfumado", "grato", "oloroso"],
  frugal: ["abundante", "copioso", "excesivo", "suntuoso", "opulento"],
  ignaro: ["sabio", "docto", "erudito", "culto", "instruido"],
  ignominioso: ["honroso", "digno", "glorioso", "noble", "decoroso"],
  inefable: ["expresable", "decible", "comunicable", "explicable", "verbal"],
  inerte: ["activo", "dinámico", "vivo", "enérgico", "vigoroso"],
  insigne: ["mediocre", "vulgar", "corriente", "común", "insignificante"],
  inusitado: ["habitual", "frecuente", "común", "corriente", "usual"],

  lábil: ["firme", "estable", "constante", "sólido", "duradero"],
  lacónico: ["locuaz", "verboso", "hablador", "elocuente", "expresivo"],
  lóbrego: ["luminoso", "radiante", "claro", "resplandeciente", "diáfano"],
  mendaz: ["veraz", "sincero", "honesto", "fidedigno", "auténtico"],
  nimio: ["considerable", "abundante", "copioso", "notable", "grande"],
  obtuso: ["agudo", "perspicaz", "sagaz", "lúcido", "penetrante"],
  ominoso: ["esperanzador", "auspicioso", "favorable", "positivo", "propicio"],
  parco: ["abundante", "copioso", "profuso", "generoso", "liberal"],
  pusilánime: ["valiente", "audaz", "intrépido", "arrojado", "osado"],
  recóndito: ["visible", "claro", "manifiesto", "patente", "evidente"],
  sórdido: ["noble", "digno", "honroso", "decoroso", "elevado"],
  taciturno: ["locuaz", "hablador", "expresivo", "elocuente", "verbal"],
  vetusto: ["moderno", "nuevo", "reciente", "actual", "contemporáneo"],
  vil: ["noble", "digno", "honrado", "íntegro", "recto"],
    acerbo: ["dulce", "suave", "agradable", "placentero", "afable"],
  aciago: ["venturoso", "feliz", "propicio", "afortunado", "favorable"],
  acrisolado: ["impuro", "manchado", "viciado", "corrupto", "adulterado"],
  adlátere: ["opositor", "adversario", "enemigo", "rival", "contrario"],
  afín: ["ajeno", "extraño", "distante", "opuesto", "disímil"],
  alfeñique: ["robusto", "fuerte", "vigoroso", "fornido", "atlético"],
  anodino: ["interesante", "relevante", "notable", "significativo", "trascendente"],
  apolíneo: ["dionisíaco", "desordenado", "caótico", "pasional", "impulsivo"],
  apodíctico: ["dudoso", "incierto", "problemático", "discutible", "cuestionable"],
  arcaizante: ["moderno", "actual", "contemporáneo", "reciente", "nuevo"],

  atávico: ["moderno", "actual", "contemporáneo", "reciente", "nuevo"],

  baldragas: ["laborioso", "aplicado", "diligente", "activo", "trabajador"],
  bastardo: ["legítimo", "auténtico", "genuino", "verdadero", "original"],
  beato: ["impío", "irreverente", "profano", "hereje", "blasfemo"],

  críptico: ["claro", "explícito", "evidente", "comprensible", "manifiesto"],

  deprecable: ["loable", "admirable", "digno", "meritorio", "estimable"],
  desabrido: ["sabroso", "gustoso", "agradable", "placentero", "delicioso"],
  desmedido: ["moderado", "mesurado", "contenido", "templado", "prudente"],
  desvaído: ["intenso", "vivo", "brillante", "resplandeciente", "radiante"],
  disímil: ["semejante", "afín", "similar", "análogo", "parecido"],
  efluvio: ["hedor", "pestilencia", "fetidez", "tufo", "mal olor"],
  elocuente: ["taciturno", "parco", "lacónico", "callado", "reservado"],
  empíreo: ["infernal", "tenebroso", "oscuro", "lóbrego", "sombrío"],
  enfático: ["tibio", "débil", "apagado", "indiferente", "apático"],

  erial: ["fértil", "fecundo", "productivo", "ubérrimo", "fructífero"],
  escueto: ["extenso", "prolijo", "verboso", "dilatado", "amplio"],
  esmirriado: ["robusto", "fornido", "vigoroso", "corpulento", "fuerte"],
  esotérico: ["exotérico", "claro", "público", "accesible", "manifiesto"],
  espurio: ["legítimo", "auténtico", "genuino", "verdadero", "real"],
  estéril: ["fértil", "fecundo", "productivo", "fructífero", "ubérrimo"],
  exánime: ["vigoroso", "animado", "fuerte", "enérgico", "robusto"],
  execrable: ["admirable", "loable", "digno", "meritorio", "estimable"],
  exiguo: ["abundante", "copioso", "numeroso", "amplio", "extenso"],


  frígido: ["ardiente", "apasionado", "fogoso", "vehemente", "intenso"],
  fútil: ["importante", "trascendente", "relevante", "significativo", "valioso"],
  hosco: ["afable", "cordial", "amable", "sociable", "benigno"],
  ignoto: ["conocido", "célebre", "famoso", "notorio", "popular"],
  infausto: ["venturoso", "feliz", "afortunado", "propicio", "favorable"],
  inmarcesible: ["caduco", "perecedero", "efímero", "transitorio", "fugaz"],
  lánguido: ["vigoroso", "enérgico", "robusto", "fuerte", "activo"],
  macilento: ["lozano", "saludable", "robusto", "fuerte", "vigoroso"],

  nefasto: ["benéfico", "favorable", "propicio", "positivo", "ventajoso"],
  prolijo: ["descuidado", "negligente", "impreciso", "desordenado", "caótico"],
  sibilino: ["claro", "evidente", "directo", "explícito", "manifiesto"],
  torvo: ["afable", "amable", "cordial", "benigno", "apacible"],
  ubérrimo: ["árido", "estéril", "yermo", "infecundo", "seco"],
  vilipendiado: ["honrado", "respetado", "estimado", "valorado", "ensalzado"],
}


