export const antonimosBloque3: Record<string, string[]> = {
  acerbo: ["dulce", "suave", "afable", "agradable", "placentero"],
  aciago: ["feliz", "venturoso", "propicio", "afortunado", "favorable"],
  acrisolado: ["impuro", "manchado", "viciado", "corrupto", "adulterado"],
  adusto: ["amable", "afable", "cordial", "benévolo", "risueño"],
  anodino: ["interesante", "relevante", "notable", "significativo", "importante"],
  apocado: ["valiente", "audaz", "intrépido", "osado", "arrojado"],
  arcano: ["evidente", "manifiesto", "claro", "patente", "visible"],
  arisco: ["afable", "sociable", "cordial", "amigable", "benigno"],
  austero: ["lujoso", "suntuoso", "fastuoso", "opulento", "ostentoso"],
  avieso: ["recto", "honrado", "íntegro", "justo", "probo"],

  baladí: ["importante", "trascendente", "grave", "esencial", "fundamental"],
  banal: ["profundo", "complejo", "trascendente", "denso", "significativo"],
  beligerante: ["pacífico", "conciliador", "tranquilo", "sereno", "apacible"],
  benévolo: ["cruel", "severo", "riguroso", "implacable", "duro"],
  caduco: ["perenne", "duradero", "constante", "permanente", "estable"],
  cáustico: ["suave", "amable", "benigno", "afable", "cordial"],
  circunspecto: ["imprudente", "temerario", "irreflexivo", "osado", "ligero"],
  contumaz: ["dócil", "flexible", "obediente", "maleable", "sumiso"],
  críptico: ["claro", "explícito", "evidente", "comprensible", "manifiesto"],
  cándido: ["malicioso", "astuto", "taimado", "pérfido", "engañoso"],

  decrépito: ["vigoroso", "robusto", "lozano", "fuerte", "saludable"],
  deleznable: ["sólido", "consistente", "firme", "estable", "resistente"],
  denodado: ["cobarde", "pusilánime", "temeroso", "apocado", "miedoso"],
  diáfano: ["opaco", "turbio", "oscuro", "nebuloso", "denso"],
  disoluto: ["austero", "sobrio", "moderado", "templado", "contenido"],
  dúctil: ["rígido", "inflexible", "férreo", "duro", "intransigente"],
  efímero: ["duradero", "perenne", "permanente", "constante", "estable"],
  elíseo: ["lóbrego", "sombrío", "triste", "aciago", "funesto"],
  estólido: ["perspicaz", "agudo", "sagaz", "lúcido", "avispado"],
  execrable: ["admirable", "loable", "digno", "meritorio", "estimable"],

  falaz: ["veraz", "sincero", "honesto", "fidedigno", "auténtico"],
  fastuoso: ["sobrio", "austero", "simple", "modesto", "humilde"],
  fatuo: ["sensato", "juicioso", "prudente", "cuerdo", "sabio"],
  frívolo: ["grave", "serio", "formal", "responsable", "sensato"],
  funesto: ["favorable", "propicio", "afortunado", "feliz", "venturoso"],
  huraño: ["afable", "sociable", "cordial", "amigable", "benigno"],
  ignaro: ["docto", "sabio", "culto", "erudito", "instruido"],
  ignominioso: ["honroso", "digno", "glorioso", "noble", "decoroso"],
  inane: ["sustancial", "profundo", "denso", "significativo", "valioso"],
  infausto: ["feliz", "afortunado", "venturoso", "propicio", "favorable"],

  inmarcesible: ["caduco", "perecedero", "efímero", "transitorio", "fugaz"],
  insigne: ["insignificante", "irrelevante", "mediocre", "oscuro", "anodino"],
  lábil: ["firme", "estable", "constante", "sólido", "duradero"],
  lacónico: ["locuaz", "verboso", "elocuente", "hablador", "expresivo"],
  lóbrego: ["luminoso", "radiante", "claro", "resplandeciente", "diáfano"],
  mendaz: ["veraz", "sincero", "honesto", "fidedigno", "auténtico"],
  nimio: ["considerable", "abundante", "copioso", "notable", "grande"],
  obtuso: ["agudo", "perspicaz", "sagaz", "lúcido", "penetrante"],
  ominoso: ["favorable", "propicio", "esperanzador", "positivo", "auspicioso"],
  parco: ["abundante", "copioso", "profuso", "generoso", "liberal"],
  pusilánime: ["valiente", "audaz", "intrépido", "arrojado", "osado"],
  pródigo: ["avaro", "tacaño", "mezquino", "ahorrativo", "económico"],
  probo: ["corrupto", "deshonesto", "vil", "ruin", "perverso"],
  recóndito: ["visible", "patente", "manifiesto", "claro", "evidente"],
  reticente: ["franco", "abierto", "expresivo", "sincero", "comunicativo"],
  sórdido: ["noble", "digno", "honroso", "decoroso", "elevado"],
  taciturno: ["locuaz", "hablador", "expresivo", "elocuente", "verbal"],
  ubérrimo: ["estéril", "árido", "yermo", "infecundo", "seco"],
  vetusto: ["moderno", "nuevo", "reciente", "actual", "contemporáneo"],
  vil: ["noble", "digno", "honrado", "íntegro", "recto"],
  acerbo2: ["dulcificado", "agradable", "placentero", "ameno", "grato"],
  adusto2: ["jovial", "festivo", "alegre", "risueño", "cordial"],
  alípede: ["torpe", "lento", "pesado", "tardo", "lerdo"],
  anodadizo: ["resuelto", "decidido", "firme", "seguro", "determinado"],
  apocado2: ["valeroso", "intrépido", "audaz", "arrojado", "osado"],
  austero2: ["fastuoso", "lujoso", "suntuoso", "ostentoso", "opulento"],
  balbucir: ["declamar", "pronunciar", "articular", "expresar", "enunciar"],
  circunspecto2: ["desenvuelto", "espontáneo", "suelto", "natural", "franco"],
  comedido: ["excesivo", "desmedido", "desbordado", "exagerado", "inmoderado"],
  cruento: ["incruento", "pacífico", "benigno", "suave", "leve"],

  deleitoso: ["desagradable", "ingrato", "áspero", "molesto", "insufrible"],
  desapacible: ["placentero", "ameno", "agradable", "grato", "delicioso"],
  desmañando: ["diestro", "hábil", "ágil", "competente", "capaz"],
  displicente2: ["cortés", "atento", "considerado", "amable", "solícito"],
  díscolo: ["obediente", "sumiso", "dócil", "disciplinado", "sujeto"],
  estólido2: ["vivaz", "avispado", "ágil", "alerta", "despierto"],
  execrable2: ["estimable", "admirable", "loable", "digno", "meritorio"],
  fúnebre: ["festivo", "alegre", "jovial", "animado", "vivo"],
  ignominioso2: ["honorable", "glorioso", "noble", "digno", "decoroso"],
  
  infausto2: ["auspicioso", "venturoso", "propicio", "favorable", "benéfico"],
  insípido: ["sabroso", "gustoso", "delicioso", "apetitoso", "agradable"],
  lánguido2: ["vigoroso", "enérgico", "activo", "dinámico", "fuerte"],
  mustio: ["animado", "jovial", "alegre", "vivaz", "entusiasta"],
  necio: ["prudente", "sensato", "cuerdo", "juicioso", "sabio"],
  oneroso: ["ligero", "leve", "sencillo", "simple", "fácil"],
  opaco: ["brillante", "resplandeciente", "luminoso", "radiante", "claro"],
  parvo: ["inteligente", "agudo", "sagaz", "perspicaz", "lúcido"],
  sórdido2: ["elegante", "refinado", "distinguido", "pulcro", "decoroso"],
  torpe: ["diestro", "hábil", "competente", "ágil", "capaz"],

  trémulo: ["firme", "seguro", "estable", "constante", "sólido"],
  vetusto2: ["nuevo", "reciente", "moderno", "actual", "contemporáneo"],
  yermo: ["fértil", "fecundo", "productivo", "fructífero", "ubérrimo"],
}

