export const antonimosBloque4: Record<string, string[]> = {
  abúlico: ["volitivo", "decidido", "resuelto", "enérgico", "determinado"],
  acerado: ["blando", "suave", "maleable", "flexible", "dúctil"],
  advenedizo: ["nativo", "originario", "autóctono", "propio", "local"],
  adusto: ["afable", "cordial", "amable", "benigno", "risueño"],
  afónico: ["sonoro", "vocal", "audible", "resonante", "claro"],
  agudo: ["obtuso", "romo", "torpe", "lerdo", "necio"],
  altilocuente: ["sencillo", "llano", "simple", "sobrio", "natural"],
  anodino: ["interesante", "relevante", "notable", "trascendente", "importante"],
  apócrifo: ["auténtico", "veraz", "fidedigno", "genuino", "real"],
  apremiante: ["aplazable", "postergable", "evitable", "prescindible", "opcional"],

  arcaico: ["moderno", "actual", "contemporáneo", "reciente", "nuevo"],
  arduo: ["fácil", "sencillo", "simple", "asequible", "accesible"],
  austero: ["lujoso", "opulento", "suntuoso", "fastuoso", "ostentoso"],
  avieso: ["recto", "íntegro", "honesto", "justo", "probo"],
  baldío: ["fértil", "productivo", "fecundo", "ubérrimo", "provechoso"],
  balbuciente: ["elocuente", "locuaz", "fluido", "expresivo", "claro"],
  belicoso: ["pacífico", "sereno", "tranquilo", "conciliador", "apacible"],
  benigno: ["cruel", "severo", "riguroso", "implacable", "duro"],
  caviloso: ["resuelto", "decidido", "determinado", "seguro", "firme"],
  ceniciento: ["radiante", "luminoso", "claro", "resplandeciente", "brillante"],

  circunspecto: ["imprudente", "temerario", "irreflexivo", "osado", "atrevido"],
  conciso: ["extenso", "prolijo", "verboso", "dilatado", "difuso"],
  contiguo: ["distante", "alejado", "separado", "remoto", "apartado"],
  contumaz: ["dócil", "obediente", "flexible", "maleable", "sumiso"],
  copioso: ["exiguo", "escaso", "mínimo", "limitado", "parco"],
  cruento: ["incruento", "pacífico", "benigno", "suave", "leve"],
  decaído: ["vigoroso", "robusto", "lozano", "fuerte", "enérgico"],
  deforme: ["hermoso", "bello", "agraciado", "armónico", "estético"],
  deleitoso: ["desagradable", "áspero", "amargo", "ingrato", "molesto"],
  denodado: ["cobarde", "pusilánime", "temeroso", "apocado", "miedoso"],

  desidioso: ["diligente", "laborioso", "aplicado", "activo", "solícito"],
  diáfano: ["opaco", "turbio", "oscuro", "nebuloso", "denso"],
  difuso: ["claro", "preciso", "definido", "concreto", "nítido"],
  disoluto: ["austero", "sobrio", "moderado", "templado", "contenido"],
  dúctil: ["rígido", "férreo", "inflexible", "duro", "intransigente"],
  efluvio: ["hedor", "fetidez", "pestilencia", "tufo", "mal olor"],
  elíptico: ["explícito", "claro", "directo", "manifiesto", "patente"],
  enhiesto: ["inclinado", "curvo", "torcido", "doblado", "encorvado"],
  errático: ["constante", "regular", "estable", "firme", "persistente"],
  estéril: ["fértil", "fecundo", "productivo", "ubérrimo", "fructífero"],

  execrable: ["admirable", "loable", "estimable", "digno", "meritorio"],
  exiguo: ["abundante", "copioso", "amplio", "numeroso", "extenso"],
  fastidioso: ["agradable", "placentero", "ameno", "deleitoso", "entretenido"],
  fétido: ["fragante", "aromático", "perfumado", "grato", "oloroso"],
  fúlgido: ["opaco", "apagado", "oscuro", "lóbrego", "sombrío"],
  funesto: ["propicio", "afortunado", "favorable", "venturoso", "feliz"],
  gravoso: ["leve", "ligero", "liviano", "suave", "sencillo"],
  hosco: ["afable", "cordial", "amable", "sociable", "benigno"],
  ignaro: ["sabio", "docto", "erudito", "culto", "instruido"],
  impávido: ["temeroso", "asustado", "miedoso", "aprehensivo", "cobarde"],
  inane: ["sustancial", "denso", "profundo", "valioso", "significativo"],
  infausto: ["feliz", "afortunado", "venturoso", "propicio", "favorable"],
  inmarcesible: ["caduco", "perecedero", "efímero", "fugaz", "transitorio"],
  insigne: ["mediocre", "vulgar", "corriente", "común", "insignificante"],
  iracundo: ["apacible", "sereno", "calmo", "sosegado", "tranquilo"],
  lánguido: ["vigoroso", "enérgico", "robusto", "fuerte", "activo"],
  lóbrego: ["luminoso", "radiante", "claro", "resplandeciente", "brillante"],
  mendaz: ["veraz", "sincero", "honesto", "fidedigno", "auténtico"],
  nefasto: ["beneficioso", "favorable", "propicio", "positivo", "ventajoso"],
  ominoso: ["esperanzador", "auspicioso", "favorable", "positivo", "propicio"],
  prolijo: ["descuidado", "negligente", "impreciso", "desordenado", "caótico"],
  recóndito: ["visible", "claro", "manifiesto", "patente", "evidente"],
  reticente: ["franco", "abierto", "expresivo", "comunicativo", "sincero"],
  sórdido: ["noble", "digno", "honroso", "decoroso", "elevado"],
  taciturno: ["locuaz", "hablador", "expresivo", "elocuente", "verbal"],
  vetusto: ["moderno", "nuevo", "reciente", "actual", "contemporáneo"],
  vil: ["noble", "honrado", "digno", "íntegro", "recto"],
}