export const antonimosBloque2: Record<string, string[]> = {
  fraterno: ["hostil", "enemigo", "antagónico", "rival", "adverso"],
  hostil: ["amigable", "fraterno", "cordial", "afable", "benévolo"],
  prolífico: ["estéril", "improductivo", "árido", "infértil", "yermo"],
  estéril: ["fértil", "prolífico", "productivo", "fecundo", "abundante"],
  efímero: ["duradero", "permanente", "estable", "constante", "perpetuo"],
  perenne: ["pasajero", "efímero", "fugaz", "transitorio", "momentáneo"],
  dócil: ["indómito", "rebelde", "insumiso", "indisciplinado", "arisco"],
  indómito: ["dócil", "sumiso", "obediente", "maleable", "disciplinado"],
  férreo: ["flexible", "blando", "maleable", "elástico", "dúctil"],
  dúctil: ["rígido", "férreo", "inflexible", "duro", "intransigente"],

  conspicuo: ["insignificante", "oscuro", "anónimo", "irrelevante", "inadvertido"],
  ignominioso: ["honroso", "digno", "glorioso", "noble", "decoroso"],
  parsimonioso: ["precipitado", "impulsivo", "acelerado", "apresurado", "vehemente"],
  tacáneo: ["generoso", "dadivoso", "liberal", "magnánimo", "altruista"],
  munífico: ["tacaño", "mezquino", "avaro", "cicatero", "ruin"],
  indolente: ["diligente", "activo", "laborioso", "aplicado", "solícito"],
  diligente: ["perezoso", "indolente", "negligente", "haragán", "remiso"],
  lóbrego: ["luminoso", "claro", "resplandeciente", "diáfano", "radiante"],
  radiante: ["lóbrego", "oscuro", "sombrío", "apagado", "turbio"],

  sobrio: ["excesivo", "desmedido", "opulento", "suntuoso", "lujoso"],
  fastuoso: ["austero", "sobrio", "simple", "modesto", "humilde"],
  lacónico: ["locuaz", "verboso", "elocuente", "hablador", "expresivo"],
  verboso: ["conciso", "breve", "lacónico", "parco", "sucinto"],
  abyecto: ["noble", "digno", "íntegro", "honrado", "recto"],
  íntegro: ["corrupto", "depravado", "vicioso", "pervertido", "ruin"],
  frígido: ["ardiente", "apasionado", "fogoso", "vehemente", "intenso"],
  apático: ["entusiasta", "ardoroso", "vehemente", "apasionado", "activo"],

  candoroso: ["malicioso", "astuto", "pérfido", "taimado", "engañoso"],
  taimado: ["sincero", "franco", "leal", "honesto", "recto"],
  fútil: ["importante", "trascendente", "relevante", "significativo", "valioso"],
  baladí: ["esencial", "grave", "serio", "importante", "trascendente"],
  nimio: ["considerable", "abundante", "copioso", "grande", "notable"],
  banal: ["profundo", "serio", "trascendente", "complejo", "denso"],

  ignaro: ["sabio", "docto", "erudito", "culto", "instruido"],
  erudito: ["ignorante", "inculto", "lego", "iletrado", "rústico"],
  tosco: ["fino", "delicado", "sutil", "elegante", "refinado"],
  refinado: ["burdo", "tosco", "grosero", "rudo", "basto"],
  huraño: ["afable", "sociable", "cordial", "amable", "benigno"],
  sociable: ["huraño", "arisco", "hosco", "retraído", "taciturno"],

  osado: ["cauto", "prudente", "precavido", "sensato", "juicioso"],
  pusilánime: ["valiente", "audaz", "intrépido", "osado", "arrojado"],
  intrépido: ["cobarde", "temeroso", "pusilánime", "miedoso", "apocado"],
  apocado: ["valiente", "resuelto", "decidido", "audaz", "osado"],
  belicoso: ["pacífico", "apacible", "tranquilo", "sereno", "conciliador"],
  conciliador: ["beligerante", "hostil", "agresivo", "belicoso", "pendenciero"],

  falaz: ["veraz", "sincero", "honesto", "auténtico", "fidedigno"],
}
