export const antonimosBloque1: Record<string, string[]> = {
  locuaz: ["taciturno", "callado", "silencioso", "reservado", "parco"],
  parco: ["locuaz", "verboso", "hablador", "elocuente", "expresivo", "abundante", "profuso", "copioso", "generoso", "liberal"],
  pródigo: ["avaro", "tacaño", "mezquino", "económico", "ahorrativo"],
  avaro: ["generoso", "dadivoso", "pródigo", "liberal", "magnánimo"],
  anodino: ["interesante", "relevante", "notable", "significativo", "importante"],
  acendrado: ["impuro", "corrupto", "viciado", "manchado", "depravado"],
  adusto: ["afable", "cordial", "amable", "benévolo", "risueño"],
  afable: ["áspero", "huraño", "adusto", "severo", "hosco"],
  ignoto: ["conocido", "célebre", "famoso", "popular", "notorio"],
  lúgubre: ["alegre", "festivo", "jovial", "luminoso", "optimista"],

  severo: ["indulgente", "benigno", "comprensivo", "tolerante", "flexible"],
  vehemente: ["apático", "indiferente", "tibio", "impasible", "insensible"],
  magnánimo: ["mezquino", "ruin", "tacaño", "avaro", "egoísta"],
  exiguo: ["abundante", "copioso", "amplio", "numeroso", "extenso", "mínimo"],
  profuso: ["escaso", "parco", "limitado", "exiguo", "mínimo"],
  irrisorio: ["considerable", "importante", "respetable", "serio", "trascendente"],
  sagaz: ["torpe", "obtuso", "necio", "lerdo", "inepto"],
  torpe: ["hábil", "diestro", "ágil", "competente", "capaz"],
  sutil: ["burdo", "tosco", "grosero", "rudo", "basto"],
  burdo: ["refinado", "delicado", "sutil", "fino", "elegante"],

  pulcro: ["sucio", "desaliñado", "descuidado", "mugriento", "andrajoso"],
  mezquino: ["generoso", "altruista", "dadivoso", "magnánimo", "liberal"],
  incauto: ["prudente", "cauto", "precavido", "sensato", "juicioso"],
  cauto: ["imprudente", "temerario", "incauto", "osado", "arriesgado"],
  prolijo: ["descuidado", "negligente", "desordenado", "impreciso", "caótico"],
  frívolo: ["serio", "formal", "grave", "responsable", "sensato"],
  parvo: ["sabio", "inteligente", "perspicaz", "agudo", "docto"],
  apacible: ["violento", "iracundo", "agresivo", "belicoso", "colérico"],

  iracundo: ["apacible", "sereno", "calmo", "sosegado", "tranquilo"],
  extenuado: ["vigoroso", "fuerte", "energético", "robusto", "vital"],
  austero: ["lujoso", "opulento", "suntuoso", "ostentoso", "fastuoso"],
  opulento: ["pobre", "mísero", "humilde", "precario", "menesteroso"],
  precario: ["sólido", "estable", "seguro", "firme", "duradero"],
  hosco: ["afable", "cordial", "amable", "sociable", "benigno"],
  benigno: ["cruel", "severo", "duro", "implacable", "riguroso"],
  altivo: ["humilde", "modesto", "sencillo", "sumiso", "llano"],
  vil: ["noble", "digno", "honrado", "íntegro", "recto"],

  nefasto: ["benéfico", "favorable", "propicio", "positivo", "ventajoso"],
  sórdido: ["noble", "digno", "honroso", "decoroso", "elevado"],
  obtuso: ["perspicaz", "sagaz", "agudo", "penetrante", "lúcido"],
  lúcido: ["confuso", "turbio", "oscuro", "ofuscado", "nublado"],
  plácido: ["turbulento", "agitado", "violento", "tempestuoso", "caótico"],
  estólido: ["perspicaz", "avispado", "sagaz", "agudo", "vivo"],
  frugal: ["abundante", "copioso", "excesivo", "opulento", "suntuoso"],
  hediondo: ["fragante", "aromático", "perfumado", "oloroso", "grato"],
  diáfano: ["opaco", "turbio", "oscuro", "nebuloso", "denso"],
  funesto: ["venturoso", "feliz", "afortunado", "propicio", "favorable"],

  pueril: ["maduro", "adulto", "sensato", "juicioso", "responsable"],
  solaz: ["fatiga", "cansancio", "agotamiento", "esfuerzo", "trabajo"],
  prócer: ["plebeyo", "vulgar", "común", "ordinario", "corriente"],
  mendaz: ["veraz", "honesto", "sincero", "fidedigno", "auténtico"],
  veraz: ["mentiroso", "falaz", "embustero", "mendaz", "falso"],
  incólume: ["dañado", "herido", "lesionado", "deteriorado", "afectado"],
  inerte: ["activo", "dinámico", "vivo", "enérgico", "vigoroso"],
  lábil: ["firme", "estable", "constante", "sólido", "duradero"],
  volátil: ["permanente", "estable", "duradero", "persistente", "constante"],
  advenedizo: ["nativo", "originario", "autóctono", "propio", "local"],
}
