export const bloque4: Record<string, string[]> = {
  afán: ["empeño", "anhelo", "deseo", "aspiración", "ilusión"],
  albor: ["amanecer", "inicio", "comienzo", "aurora", "origen"],
  baldío: ["estéril", "inútil", "improductivo", "yermo", "desierto"],
  cándido: ["ingenuo", "inocente", "sincero", "simple", "confiado"],
  clamor: ["grito", "protesta", "reclamo", "vociferación", "alboroto"],
  destello: ["brillo", "fulgor", "resplandor", "centella", "chispa"],
  dislate: ["absurdo", "error", "despropósito", "disparate", "insensatez"],
  efigie: ["imagen", "figura", "retrato", "estatua", "semblanza"],
  fragor: ["estruendo", "ruido", "estallido", "retumbo", "clamor"],
  hastío: ["cansancio", "aburrimiento", "fatiga", "tedio", "saturación"],
  ignominia: ["vergüenza", "deshonra", "afrenta", "infamia", "ultraje"],
  ímpetu: ["fuerza", "energía", "vigor", "impulso", "vehemencia"],
  jactancia: ["arrogancia", "presunción", "alarde", "vanagloria", "soberbia"],
  lisonja: ["halago", "adulación", "elogio", "cumplido", "piropo"],
  mesura: ["moderación", "prudencia", "templanza", "cordura", "equilibrio"],
  oprobio: ["vergüenza", "deshonra", "afrenta", "ultraje", "ignominia"],
  plácido: ["tranquilo", "sereno", "calmo", "sosegado", "apacible"],
  quietud: ["calma", "reposo", "silencio", "inmovilidad", "paz"],
  recelo: ["desconfianza", "sospecha", "duda", "prevención", "temor"],
  sosiego: ["tranquilidad", "calma", "serenidad", "quietud", "paz"],
  tesón: ["perseverancia", "tenacidad", "constancia", "firmeza", "empeño"],
  vigor: ["fuerza", "energía", "robustez", "ímpetu", "potencia"],
}
