export const bloque5: Record<string, string[]> = {
  audaz: ["osado", "valiente", "intrépido", "temerario", "arrojado"],
  benigno: ["bondadoso", "amable", "clemente", "piadoso", "afable"],
  colosal: ["enorme", "gigantesco", "inmenso", "monumental", "magno"],
  dócil: ["sumiso", "obediente", "maleable", "apacible", "mansedumbre"],
  errático: ["inestable", "voluble", "irregular", "cambiante", "impredecible"],
  férreo: ["duro", "rígido", "inflexible", "severo", "estricto"],
  grácil: ["elegante", "esbelto", "delicado", "ligero", "fino"],
  hostil: ["enemigo", "agresivo", "adverso", "beligerante", "opuesto"],
  ínfimo: ["mínimo", "diminuto", "nimio", "insignificante", "exiguo"],
  jovial: ["alegre", "animado", "festivo", "contento", "risueño"],
  loable: ["digno", "meritorio", "encomiable", "honorable", "estimable"],
  meticuloso: ["cuidadoso", "prolijo", "esmerado", "preciso", "pulcro"],
  nocivo: ["perjudicial", "dañino", "tóxico", "maligno", "corrosivo"],
  oneroso: ["costoso", "caro", "gravoso", "pesado", "excesivo"],
  pérfido: ["traidor", "desleal", "vil", "malicioso", "infame"],
  raudo: ["veloz", "rápido", "ligero", "ágil", "pronto"],
  severo: ["rígido", "estricto", "duro", "adusto", "austero"],
  tósigo: ["veneno", "toxina", "ponzoña", "droga", "sustancia letal"],
  ubérrimo: ["abundante", "fértil", "opulento", "copioso", "pródigo"],
  zéloso: ["cuidadoso", "solícito", "atento", "esmerado", "diligente"],
}
